openapi: 3.0.3
info:
  title: KT API
  description: Kernel tracer API description
  version: 1.0.0
servers:
  - url: https://rh-ks-nav.swagger.io/api
tags:
  - name: symbols
    description: Kernel symbols
  - name: files
    description: Kernel files
paths:
  /files:
    get:
      tags:
        - files
      summary: Gets all files
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/File"
        "400":
          description: Invalid status value
  /files/{fileId}:
    get:
      tags:
        - files
      summary: Find File by ID
      description: Returns a single File
      operationId: getFileById
      parameters:
        - name: fileId
          in: path
          description: ID of File to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/File"
        "400":
          description: Invalid ID supplied
        "404":
          description: File not found
  /files/{symbolId}:
    get:
      tags:
        - files
      summary: Find files by symbol ID
      description: Returns files linked to a symbol ID
      operationId: getFilesBySymbolId
      parameters:
        - name: symbolId
          in: path
          description: ID of symbol to filter symbols by
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/File"
        "400":
          description: Invalid ID supplied
        "404":
          description: File not found
  /symbols:
    get:
      tags:
        - symbols
      summary: Gets all symbols
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Symbol"
        "400":
          description: Invalid status value
  /symbols/{symbolId}:
    get:
      tags:
        - symbols
      summary: Find Symbol by ID
      description: Returns a single Symbol
      operationId: getSymbolById
      parameters:
        - name: symbolId
          in: path
          description: ID of Symbol to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Symbol"
        "400":
          description: Invalid ID supplied
        "404":
          description: Symbol not found
  /symbols/{fileId}:
    get:
      tags:
        - symbols
      summary: Find symbols by File ID
      description: Returns symbols linked to an File ID
      operationId: getSymbolsByFileId
      parameters:
        - name: fileId
          in: path
          description: ID of File to filter symbols by
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Symbol"
        "400":
          description: Invalid ID supplied
        "404":
          description: Symbol not found
  /symbols/{instanceId}:
    get:
      tags:
        - symbols
      summary: Find symbols by Instance ID
      description: Returns symbols linked to an Instance ID
      operationId: getSymbolsByInstanceId
      parameters:
        - name: instanceId
          in: path
          description: ID of Instance to filter symbols by
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Symbol"
        "400":
          description: Invalid ID supplied
        "404":
          description: Symbol not found
components:
  schemas:
    File:
      required:
        - id
        - name
        - sourceCode
        - symbolIds
        - symbolMap
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: arch/arm64/kernel/alternative.c
        sourceCode:
          type: string
          format: text/plain; charset=UTF-8
          example: \u0076\u006f\u0069\u0064\u0020\u0070\u0075\u0074\u005f\u0075\u006e\u0075\u0073\u0065\u0064\u005f\u0066\u0064\u0028\u0075\u006e\u0073\u0069\u0067\u006e\u0065\u0064\u0020\u0069\u006e\u0074\u0020\u0066\u0064\u0029\u000a\u007b\u000a\u0020\u0020\u0073\u0074\u0072\u0075\u0063\u0074\u0020\u0066\u0069\u006c\u0065\u0073\u005f\u0073\u0074\u0072\u0075\u0063\u0074\u0020\u002a\u0066\u0069\u006c\u0065\u0073\u0020\u003d\u0020\u0063\u0075\u0072\u0072\u0065\u006e\u0074\u002d\u003e\u0066\u0069\u006c\u0065\u0073\u003b\u000a\u0020\u0020\u0073\u0070\u0069\u006e\u005f\u006c\u006f\u0063\u006b\u0028\u0026\u0066\u0069\u006c\u0065\u0073\u002d\u003e\u0066\u0069\u006c\u0065\u005f\u006c\u006f\u0063\u006b\u0029\u003b\u000a\u0020\u0020\u005f\u005f\u0070\u0075\u0074\u005f\u0075\u006e\u0075\u0073\u0065\u0064\u005f\u0066\u0064\u0028\u0066\u0069\u006c\u0065\u0073\u002c\u0020\u0066\u0064\u0029\u003b\u000a\u0020\u0020\u0073\u0070\u0069\u006e\u005f\u0075\u006e\u006c\u006f\u0063\u006b\u0028\u0026\u0066\u0069\u006c\u0065\u0073\u002d\u003e\u0066\u0069\u006c\u0065\u005f\u006c\u006f\u0063\u006b\u0029\u003b\u000a\u007d\u000a\u000a\u0045\u0058\u0050\u004f\u0052\u0054\u005f\u0053\u0059\u004d\u0042\u004f\u004c\u0028\u0070\u0075\u0074\u005f\u0075\u006e\u0075\u0073\u0065\u0064\u005f\u0066\u0064\u0029\u003b
        symbolIds:
          type: array
          example: [1, 2, 3]
          items:
            type: number
        symbolMap:
          type: object
          description: Maps source symbols to all target symbols
          example:
            {
              "__x64_sys_ioctl": ["ksys_ioctl"],
              "ksys_ioctl": ["fput", "do_vfs_ioctl", "__fdget", "security_file_ioctl"],
              "fput": ["fput_many"],
              "fput_many": ["queue_delayed_work_on", "task_work_add", "llist_add_batch"],
            }
          items:
            type: array
    Symbol:
      required:
        - id
        - instanceId
        - name
        - fileIds
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: "__x64_sys_open"
        instanceId:
          type: integer
          format: int64
          example: 10
        fileIds:
          type: array
          example: [1, 2, 3]
          items:
            type: number
